# Generated by Django 3.0.14 on 2022-06-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20220620_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='coid',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='mail',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mail',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='ta',
            name='mail',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='ta',
            name='status',
            field=models.CharField(default='Not Assigned', max_length=20),
        ),
    ]
