# Generated by Django 3.0.14 on 2022-06-21 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20220621_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='count',
            new_name='number_of_TA',
        ),
    ]
