# Generated by Django 3.0.5 on 2022-06-10 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coordinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coid', models.CharField(max_length=10)),
                ('pwd', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('courseid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=8)),
                ('mail', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('star', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.course')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=8)),
                ('mail', models.CharField(max_length=30)),
                ('batch', models.IntegerField()),
                ('sid', models.IntegerField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.course')),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=8)),
                ('mail', models.CharField(max_length=30)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.course')),
            ],
        ),
    ]
