# Generated by Django 3.0.5 on 2022-06-12 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('user_type', models.CharField(choices=[(1, 'coordinator'), (2, 'faculty'), (3, 'Student'), (4, 'TA')], default=1, max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='faculty',
            name='mail',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='mail',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ta',
            name='mail',
            field=models.EmailField(max_length=30),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Main.user')),
            ],
        ),
    ]
