# Generated by Django 3.0.14 on 2022-06-17 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ta',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.course'),
        ),
        migrations.AlterField(
            model_name='ta',
            name='star',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ta',
            name='status',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
