# Generated by Django 3.0.5 on 2022-06-12 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20220612_1306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
