# Generated by Django 3.0.5 on 2022-06-14 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
