# Generated by Django 3.0.14 on 2022-06-24 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20220621_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.course'),
        ),
    ]
