# Generated by Django 3.0.5 on 2022-06-16 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_delete_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='count',
            new_name='number_of_TA',
        ),
    ]
