# Generated by Django 3.0.5 on 2022-06-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_auto_20220616_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='Ta',
            field=models.ManyToManyField(to='Main.ta'),
        ),
    ]
