# Generated by Django 3.0.5 on 2022-06-16 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_faculty_ta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='Ta',
        ),
        migrations.AlterField(
            model_name='ta',
            name='cid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.course'),
        ),
    ]
