# Generated by Django 3.0.5 on 2022-06-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_auto_20220616_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='ta',
            field=models.ManyToManyField(blank=True, null=True, to='Main.ta'),
        ),
    ]
