# Generated by Django 3.0.5 on 2022-06-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_remove_faculty_ta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ta',
            name='mail',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='ta',
            name='star',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ta',
            name='status',
            field=models.CharField(default='Not Assigned', max_length=20),
        ),
    ]
