# Generated by Django 3.0.5 on 2022-06-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_auto_20220621_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ta',
            name='status',
            field=models.CharField(default='Not Assigned', max_length=12),
        ),
    ]
