# Generated by Django 4.0.4 on 2022-06-29 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_auto_20220621_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='stipendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Not approved yet', 'Not approved')], default='Not approved yet', max_length=20)),
                ('message', models.CharField(blank=True, max_length=100)),
                ('CourseObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.course')),
                ('FacultyObj', models.ForeignKey(null='False', on_delete=django.db.models.deletion.CASCADE, to='Main.faculty')),
                ('TAObj', models.ForeignKey(null='False', on_delete=django.db.models.deletion.CASCADE, to='Main.ta')),
            ],
        ),
    ]
