# Generated by Django 3.0.5 on 2022-06-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_auto_20220630_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='an',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ta',
            name='an',
            field=models.BooleanField(default=False),
        ),
    ]
