# Generated by Django 4.0.4 on 2022-07-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0018_auto_20220630_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stipendrequest',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Not approved yet', 'Not approved'), ('Disapproved', 'Disapproved')], default='Not approved yet', max_length=20),
        ),
    ]
