# Generated by Django 4.0.4 on 2022-07-01 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0020_alter_stipendrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stipendrequest',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Not approved yet', 'Not approved yet'), ('Disapproaaved', 'Disapproved')], default='Not approved yet', max_length=20),
        ),
        migrations.CreateModel(
            name='ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=1)),
                ('CourseObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.course')),
                ('TAObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.ta')),
                ('studentObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.student')),
            ],
        ),
    ]
