# Generated by Django 4.0.4 on 2022-07-01 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0021_alter_stipendrequest_status_ratings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ratings',
            new_name='rating',
        ),
    ]
